# @package _global_

to_tensor:
  _target_: emg2qwerty.transforms.ToTensor
  fields: [emg_left, emg_right]

band_rotation:
  _target_: emg2qwerty.transforms.ForEach
  transform:
    _target_: emg2qwerty.transforms.RandomBandRotation
    offsets: [-1, 0, 1]

temporal_jitter:
  _target_: emg2qwerty.transforms.TemporalAlignmentJitter
  max_offset: 120

logspec:
  _target_: emg2qwerty.transforms.LogSpectrogram
  n_fft: 64
  hop_length: 16

specaug:
  _target_: emg2qwerty.transforms.SpecAugment
  n_time_masks: 3
  time_mask_param: 25
  n_freq_masks: 2
  freq_mask_param: 4

extra_train_transform:
  _target_: emg2qwerty.transforms.Compose
  transforms:
    - _target_: emg2qwerty.transforms.RandomGain
      min_gain: 0.85
      max_gain: 1.15
      per_channel: false
      p: 1.0

datamodule:
  copies_per_sample: 1
  extra_train_transform: ${extra_train_transform}

transforms:
  train:
    - ${to_tensor}
    - ${band_rotation}
    - ${temporal_jitter}
    - ${logspec}
    - ${specaug}

  val:
    - ${to_tensor}
    - ${logspec}

  test: ${transforms.val}